/*
Query Name: Customer Lifetime Revenue
Purpose: Calculate the total successful payment revenue generated by each customer.
Business Question: How much revenue has each customer generated over their lifetime?
Tables Used:
  - subscriptions
  - payments
Key Columns Used:
  - customer_id
  - subscription_id
  - amount
  - payment_status
Assumptions:
  - Only successful payments contribute to revenue
  - Revenue is calculated on a cash basis
Output:
  - customer_id
  - lifetime_revenue
*/

SELECT
    subscriptions.customer_id,
    ROUND(SUM(payments.amount::NUMERIC), 1) AS lifetime_revenue
FROM subscriptions
JOIN payments
    ON subscriptions.subscription_id = payments.subscription_id
WHERE payments.payment_status = 'successful'
GROUP BY subscriptions.customer_id
ORDER BY subscriptions.customer_id;