/*
Query Name: Revenue by Plan Type
Purpose: Calculate total revenue generated by each subscription plan.
Business Question: Which subscription plans contribute the most revenue?
Tables Used:
  - subscriptions
  - payments
Key Columns Used:
  - subscription_id
  - plan_type
  - amount
  - payment_status
Assumptions:
  - Only successful payments contribute to revenue
  - Revenue is calculated on a cash basis (payments received)
  - Subscriptions without successful payments are excluded
Output:
  - plan_type
  - total_revenue
*/

SELECT
    plan_type,
    ROUND(SUM(amount::NUMERIC), 1) AS total_revenue
FROM subscriptions
JOIN payments
    ON subscriptions.subscription_id = payments.subscription_id
WHERE payment_status = 'successful'
GROUP BY plan_type
ORDER BY total_revenue DESC;