/*
Query Name: Revenue by Acquisition Channel
Purpose: Calculate total revenue generated by customers from each acquisition channel.
Business Question: Which acquisition channels contribute the most revenue?
Tables Used:
  - customers
  - subscriptions
  - payments
Key Columns Used:
  - customer_id
  - subscription_id
  - acquisition_channel
  - amount
  - payment_status
Assumptions:
  - Only successful payments contribute to revenue
  - Revenue is calculated on a cash basis (payments received)
  - Channels are assigned at the customer level
Output:
  - acquisition_channel
  - total_revenue
*/

SELECT
    acquisition_channel,
    ROUND(SUM(amount::NUMERIC), 1) AS total_revenue
FROM customers
JOIN subscriptions
    ON customers.customer_id = subscriptions.customer_id
JOIN payments
    ON subscriptions.subscription_id = payments.subscription_id
WHERE payments.payment_status = 'successful'
GROUP BY customers.acquisition_channel
ORDER BY total_revenue DESC;